### ISSUE TITLE
No linux version ?

### ISSUE THREAD

**Issue by foxdog05000** [FlorianFe/PaperCubes#3]
Hi, I have a friend who would like to use your app, but he doesn't have windows but Linux. Is it a forgetfulness or a choice on your part not to put the Linux version in your releases ?

😍 I'm love it your 3d schematic preview !

**Comment by foxdog05000** [comment]
I understand:) Thank you for your work!

**Comment by FlorianFe** [comment]
I added a Linux build =) 
I hope it works on your friends Linux system

**Comment by foxdog05000** [comment]
👍 🎉Oh yeahhh ! Working perfectly, thanks for you job ! My friend is very happy !
Nice day !

**Comment by FlorianFe** [comment]
nice! =)
